//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyrsovik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.Sales = new HashSet<Sales>();
        }
    
        public int ID_product { get; set; }
        public int ID_owner { get; set; }
        public int ID_status { get; set; }
        public int ID_category { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
        public byte[] Photo { get; set; }
        public int Num_off { get; set; }
        public System.DateTime Data_start { get; set; }
        public System.DateTime Data_end { get; set; }
        public string Commentary { get; set; }
    
        public virtual Catygories Catygories { get; set; }
        public virtual Owners Owners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales> Sales { get; set; }
        public virtual Statuses Statuses { get; set; }
    }
}
