//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyrsovik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int ID_sale { get; set; }
        public int ID_product { get; set; }
        public int ID_staff { get; set; }
        public System.DateTime Data_sale { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
