//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4_task.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Tour = new HashSet<Tour>();
        }
    
        public int Id_country { get; set; }
        public string Name_country { get; set; }
    
        public virtual ICollection<Tour> Tour { get; set; }
    }
}
