//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4_task.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        public Tour()
        {
            this.Request = new HashSet<Request>();
        }
    
        public int Id_tour { get; set; }
        public int Id_country { get; set; }
        public int Id_manager { get; set; }
        public string Name_tour { get; set; }
        public string Description_tour { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Managers Managers { get; set; }
        public virtual ICollection<Request> Request { get; set; }
    }
}
